name: notifai-server
services:
- name: web-server
  environment_slug: node-js
  run_command: "npm start"
  github:
    repo: 2022phyro/notifications
    branch: main
    deploy_on_push: true 
  source_dir: server
  envs:
  - key: TARGET_COMPONENT
    value: "grpcsvc:5500"
    scope: RUN_TIME
- name: grpc-server
  internal_ports:
    - 5500
    - protocol: tcp
  environment_slug: node-js
  run_command: "npm run start-grpc"
  github:
    repo: 2022phyro/notifications
    branch: main
    deploy_on_push: true
  source_dir: server
  routes:
    - path: /grpc
